### ISSUE TITLE
运行main.py报错（python3.9，已安装第三方库requirements.txt）

### ISSUE THREAD

**Issue by yzliufujin** [cls0702/JD_MAOTAI#1]
谁能帮忙看看是什么问题：

错误提示如下：
Traceback (most recent call last):
  File "D:\Python\JD_MAOTAI-main\main.py", line 23, in <module>
    jd_seckill = JdSeckill()
  File "D:\Python\JD_MAOTAI-main\maotai\jd_spider_requests.py", line 281, in __init__
    self.timers = Timer()
  File "D:\Python\JD_MAOTAI-main\maotai\timer.py", line 49, in __init__
    self.diff_time = self.local_jd_time_diff()
  File "D:\Python\JD_MAOTAI-main\maotai\timer.py", line 73, in local_jd_time_diff
    return self.local_time() - self.jd_time()
  File "D:\Python\JD_MAOTAI-main\maotai\timer.py", line 58, in jd_time
    js = json.loads(ret)
  File "D:\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yzliufujin** [comment]
补充：直接运行打包的exe文件，同样报错。

**Comment by Ah-yuan** [comment]
获取到的值有问题，这个应该是不可用来。

**Comment by yzliufujin** [comment]
您好，您的邮件已收到。谢谢您！【系统自动回复】
